BasP-MR-75: Shared Input
BaSP-m2023/juvi-megarocket-app pull request #19
Opened 2023-06-05 05:02 UTC by Gianluca27

Created input component.
Added to style to input.

2023-06-05 11:42 UTC, NicolasKler approved these changes

2023-06-05 13:51 UTC, Roberto-Orazi requested changes
Hi, you should add a label tag, and the type of the input is variable, because we have different types of inputs, like password for ex

2023-06-05 15:39 UTC, Gianluca27 commented
> Hi, you should add a label tag, and the type of the input is variable, because we have different types of inputs, like password for ex

The input is made a type text input since not many of the entities have a different type. I didn't understand the part about the password, for what I've tested you can use this input for the email, name, password or any other field. Please, do you care to explain to me again?

2023-06-06 01:58 UTC, CavalloFede approved these changes

2023-06-06 02:48 UTC, leo-balonchard approved these changes
:ok_hand::ok_hand:

2023-06-06 06:04 UTC, Roberto-Orazi approved these changes

2023-06-06 13:56 UTC, merged