BaSP-MR-62: Subscriptions screen [WIP]
BaSP-m2023/juvi-megarocket-app pull request #4
Opened 2023-05-30 20:17 UTC by leo-balonchard

In progress...

2023-05-30 22:07 UTC, CavalloFede requested changes

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/Table/index.jsx
> +                      <option value="646014b31c70e12b863ad70a">Juan Manuel Lopez</option>
same as before, we need to change those hardcode ids to ones that we are sure exist on the DB

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/Table/index.jsx
> +              {expandedRows.includes(item._id) && (
We are missing the class on the edit form

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/index.jsx
> +        console.error('Error:', error);
we can delete de console.log

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/Form/index.jsx
> +        console.log(data);
We can delete console.log

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/Table/index.jsx
> +        console.log(data);
We can delete console.log

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/Table/index.jsx
> +        console.log(data);
We can delete console.log

2023-05-30 22:07 UTC, CavalloFede commented on src/Components/Subscriptions/Table/index.jsx
> +        console.log(data);
We can delete console.log

2023-06-01 00:12 UTC, CavalloFede approved these changes

2023-06-01 01:01 UTC, iaracriscenti approved these changes
🚀

2023-06-01 01:03 UTC, merged