MR-204: add test id for profile of form
BaSP-m2023/juvi-megarocket-app pull request #97
Opened 2023-07-15 23:18 UTC by VictoriaNegrotto

added new test id about form on profile of  admin

2023-07-16 00:53 UTC, Micaela-Rossi requested changes
SAme as the first file for the second, but i don't know if it's okay because i think vercel doesn't load my changes yet... please wait

2023-07-16 00:53 UTC, Micaela-Rossi commented on src/Components/Admin/Admins/Form/index.jsx
> +        <div className={styles.formContainer} testId="admin-form">
following the style we use for name the other tests id this should be admin-profile-form

2023-07-16 00:53 UTC, Micaela-Rossi commented on src/Components/Admin/Admins/Form/index.jsx
>              <Input
In the lines 187, 188 and 192 i think you need to add the test id for the buttons like <Button type="confirm" testId="confirm-button"></Button>... i do this, but wait to confirm if it work's in my pr to change it

2023-07-16 23:05 UTC, IgnacioCanton commented on src/Components/Admin/Admins/Form/index.jsx
> +        <div className={styles.formContainer} testId="admin-form">
this should be data-testid="superAdmin-admin-form"

2023-07-16 23:06 UTC, IgnacioCanton commented on src/Components/Admin/Admins/Profile/index.js
> +        <div className={styles.formContainer} testId="admin-form">
also this = data-testid="admin-profile-form"

2023-07-16 23:43 UTC, IgnacioCanton approved these changes
looks good to me

2023-07-17 00:09 UTC, NicolasKler approved these changes

2023-07-17 00:12 UTC, Micaela-Rossi approved these changes

2023-07-17 00:14 UTC, merged